# -*- coding: utf-8 -*-
"""TITANIC ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-mFvvN7Tx_KSdiChUQvPstwHfmkEuCI

## Part 1: Data Loading & Initial Inspection - Titanic Dataset
"""

# Import pandas for data manipulation
import pandas as pd

# Load the Titanic dataset from the specified URL
# Note: While the assignment mentioned Kaggle, it's often easier to directly load from a raw CSV link.
# I'll use a common raw CSV link for the Titanic dataset for simplicity.
titanic_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

# Display the first 10 rows of the DataFrame
print("First 10 rows of the Titanic dataset:")
display(titanic_df.head(10))

# Examine the number of rows and columns
print(f"\nNumber of rows: {titanic_df.shape[0]}")
print(f"Number of columns: {titanic_df.shape[1]}")

# Examine data types and non-null values
print("\nData types and non-null counts:")
titanic_df.info()

# Check for missing values
print("\nMissing values per column:")
print(titanic_df.isnull().sum())

# Check for duplicate records
num_duplicates = titanic_df.duplicated().sum()
print(f"\nNumber of duplicate records: {num_duplicates}")

# Generate summary statistics for numerical columns
print("\nSummary statistics for numerical columns:")
display(titanic_df.describe(include='number'))

# Generate summary statistics for all columns (including categorical)
print("\nSummary statistics for all columns (including categorical):")
display(titanic_df.describe(include='all'))

# Display the entire DataFrame
display(titanic_df)

import pandas as pd

titanic = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
print("="*70)
print(f"Number of rows: {titanic.shape[0]}")
print(f"Number of columns: {titanic.shape[1]}")
print("="*70)

print("\nData types and non-null counts:")
titanic.info()

print("\nMissing values per column:")
print(titanic.isnull().sum())

num_duplicates = titanic.duplicated().sum()
print(f"\nNumber of duplicate records: {num_duplicates}")

print("\nSummary statistics for numerical columns:")
display(titanic.describe(include='number'))

print("\nSummary statistics for all columns (including categorical):")
display(titanic.describe(include='all'))

"""### Revisiting Data Cleaning: Handling 'Age' and 'Cabin'

Given the insights about the predictive power of 'Age', I will re-evaluate its handling. I'll reload the original dataset to ensure the 'Age' column is present and then impute its missing values. Afterwards, I will proceed with creating the 'Has_Cabin' feature from the 'Cabin' column as previously discussed.
"""

# Reload the original dataset to restore the 'Age' column
import pandas as pd
titanic = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

print("Original 'Age' column restored. Missing values in 'Age':")
print(titanic['Age'].isnull().sum())

# Impute missing 'Age' values with the median
median_age = titanic['Age'].median()
titanic['Age'].fillna(median_age, inplace=True)

print(f"Missing 'Age' values imputed with the median: {median_age}")
print("Missing values in 'Age' after imputation:")
print(titanic['Age'].isnull().sum())

# Display info again to confirm imputation
print("\nUpdated Data types and non-null counts after 'Age' imputation:")
titanic.info()

"""Now that 'Age' has been handled, let's proceed with creating the 'Has_Cabin' feature and dropping the original 'Cabin' column, as discussed earlier."""

import pandas as pd

# Create 'Cabin_Known' feature from 'Cabin' column
# This will be 1 if Cabin is not null, and 0 if it is null
titanic['Cabin_Known'] = titanic['Cabin'].apply(lambda x: 0 if pd.isnull(x) else 1)

# Drop the redundant 'Has_Cabin' column if it exists
if 'Has_Cabin' in titanic.columns:
    titanic.drop('Has_Cabin', axis=1, inplace=True)

# Display the value counts for the new 'Cabin_Known' column
print("\nValue counts for 'Cabin_Known':")
print(titanic['Cabin_Known'].value_counts())

# Keep the original 'Cabin' column as per user's instruction.
# The information about its presence/absence is now captured by 'Cabin_Known'.

# Display info again to show final changes
print("\nFinal Data types and non-null counts after processing 'Cabin_Known':")
titanic.info()

"""### Handling Missing 'Embarked' Values

Now, let's address the two missing values in the 'Embarked' column. For categorical features with a small number of missing entries, imputing with the mode (most frequent value) is a common and effective strategy.
"""

# Find the most frequent value (mode) in the 'Embarked' column
most_frequent_embarked = titanic['Embarked'].mode()[0]

# Fill missing 'Embarked' values with the mode, assigning the result back to the column
titanic['Embarked'] = titanic['Embarked'].fillna(most_frequent_embarked)

print(f"Missing 'Embarked' values imputed with the mode: '{most_frequent_embarked}'")
print("Missing values in 'Embarked' after imputation:")
print(titanic['Embarked'].isnull().sum())

# Display the updated value counts for 'Embarked'
print("\nValue counts for 'Embarked' after imputation:")
print(titanic['Embarked'].value_counts())

# Display info again to confirm imputation
print("\nUpdated Data types and non-null counts after 'Embarked' imputation:")
titanic.info()

"""### Passengers with Originally Missing 'Embarked' Values

To see the passengers whose 'Embarked' information was originally missing, we'll look at the `titanic_df` DataFrame, which retains the initial loaded data before any imputation.
"""

missing_embarked_passengers = titanic_df[titanic_df['Embarked'].isnull()]
display(missing_embarked_passengers)

titanic[titanic["Ticket"] == "their_ticket_number"]

print("Missing values after all imputations:")
print(titanic.isnull().sum())

"""You're right to connect ticket and cabin information! People sharing the same ticket and cabin were very likely traveling together, and often related. Let's look at the passengers who shared the ticket `113572` and cabin `B28`."""

shared_ticket_cabin_passengers = titanic[(titanic['Ticket'] == '113572') & (titanic['Cabin'] == 'B28')]
display(shared_ticket_cabin_passengers)

print(f"Current shape of the titanic DataFrame: {titanic.shape}")

"""## Part 1: Data Loading & Initial Inspection - Titanic Dataset - Report

**Dataset Structure:**
*   The Titanic dataset was loaded into a pandas DataFrame named `titanic` (and `titanic_df` for original reference).
*   It contains **891 rows** and **12 columns** (original), and now **13 columns** after feature engineering.

**Data Types:**
*   **Numerical:** `PassengerId` (int64), `Survived` (int64), `Pclass` (int64), `Age` (float64), `SibSp` (int64), `Parch` (int64), `Fare` (float64).
*   **Categorical/Object:** `Name` (object), `Sex` (object), `Ticket` (object), `Cabin` (object), `Embarked` (object).
*   A new feature `Cabin_Known` (int64) was added, indicating the presence (1) or absence (0) of cabin information.

**Missing Values:**
*   **`Age`**: Originally 177 missing values, now imputed with the median (28.0).
*   **`Cabin`**: 687 missing values. This column was retained, but its information for modeling is captured by the `Cabin_Known` feature.
*   **`Embarked`**: Originally 2 missing values, now imputed with the mode ('S').

**Duplicate Records:**
*   No duplicate records were found in the dataset.

**Summary Statistics:**
*   `describe()` and `info()` output (available in previous cells) provide detailed statistical summaries for numerical columns (mean, std, min, max, quartiles) and non-null counts and data types for all columns respectively. These show reasonable ranges for numerical features and an overview of categorical distributions.

**Data Quality:**
*   The dataset is generally clean with clearly identified missing values in `Age`, `Cabin`, and `Embarked`, which have been addressed through imputation or feature engineering (`Cabin_Known`). No duplicates were found.

## Part 2: Data Preprocessing - Titanic Dataset

### A. Missing Value Treatment

1.  **Identify columns with missing values:**
    *   `Age`: 177 missing values.
    *   `Cabin`: 687 missing values.
    *   `Embarked`: 2 missing values.

2.  **Treatment:**
    *   **`Age`**: Imputed with the **median (28.0)**.
        *   **Reasoning:** Age is a numerical feature, and the median is robust to outliers, making it a suitable choice to fill missing values without distorting the distribution significantly.
    *   **`Cabin`**: Not directly imputed. Instead, a new binary feature **`Cabin_Known`** was created (0 if `Cabin` is null, 1 if not null). The original `Cabin` column was retained.
        *   **Reasoning:** The `Cabin` column has a very high percentage of missing values (approx. 77%). Direct imputation would be difficult and likely introduce noise. Creating `Cabin_Known` preserves the information of whether cabin data was available, which can be a significant predictor, without trying to guess specific cabin numbers. The user requested to keep the original `Cabin` column.
    *   **`Embarked`**: Imputed with the **mode ('S')**.
        *   **Reasoning:** `Embarked` is a categorical feature with only 2 missing values. Imputing with the mode (the most frequent port) is a standard practice for categorical data with a small number of missing entries, as it maintains the overall distribution of the column and avoids losing valuable rows.
"""

# Display missing values after all treatments to confirm
print("Missing values after all treatments:")
print(titanic.isnull().sum())

"""### B. Duplicate Removal"""

# Identify duplicate records
duplicates_before = titanic.duplicated().sum()
print(f"Number of duplicate records BEFORE removal: {duplicates_before}")

# Remove duplicates if they exist
titanic.drop_duplicates(inplace=True)

# Report the number of records removed
duplicates_after = titanic.duplicated().sum()
records_removed = duplicates_before - duplicates_after
print(f"Number of records removed: {records_removed}")
print(f"Number of duplicate records AFTER removal: {duplicates_after}")

# Verify the new shape of the DataFrame
print(f"New shape of the DataFrame after duplicate removal: {titanic.shape}")

"""### C. Outlier Detection & Treatment"""

import matplotlib.pyplot as plt
import seaborn as sns

# Select numerical columns for outlier detection
numerical_cols = titanic.select_dtypes(include=['int64', 'float64']).columns.tolist()
# Exclude 'PassengerId' as it's an identifier and not a true numerical feature for analysis
# Also exclude 'Survived' and 'Pclass' as they are often treated as categorical or target, not for outlier treatment in this context.
# 'Cabin_Known' is binary, so not suitable for boxplot outlier detection.
numerical_cols_for_outliers = [col for col in numerical_cols if col not in ['PassengerId', 'Survived', 'Pclass', 'Cabin_Known']]

print("Generating boxplots for outlier detection in numerical columns...")

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols_for_outliers):
    plt.subplot(2, 3, i + 1) # Adjust subplot grid based on number of columns
    sns.boxplot(y=titanic[col])
    plt.title(f'Boxplot of {col}')
    plt.ylabel('') # Remove y-axis label to avoid clutter
plt.tight_layout()
plt.show()

print("\nDecision on outliers:")
print(" - **Age:** There are some values above the upper whisker, but these could represent actual older passengers and should generally be retained as they are plausible and not data entry errors. The previous median imputation handled any missing values, and retaining the range of ages is important.")
print(" - **SibSp (Siblings/Spouses Aboard):** Outliers exist with higher numbers of siblings/spouses. These are plausible given family sizes and travel groups, so they should be retained. Removing them would mean removing entire family groups.")
print(" - **Parch (Parents/Children Aboard):** Similar to SibSp, higher values indicate larger family groups. These are likely legitimate data points and should be retained.")
print(" - **Fare:** This column shows significant outliers, indicating some passengers paid very high fares. These are genuine data points reflecting different classes and cabin types, and removing them would lead to a loss of information about wealth disparity. Capping or transforming might be considered for model training, but for now, they should be retained in the raw form. For this assignment, we will retain them as they are genuine data points.")

"""### D. Categorical Variable Encoding

For categorical variables, we need to convert them into numerical representations. We will use:
*   **Label Encoding** for binary categorical features like `Sex`.
*   **One-Hot Encoding** for multi-class categorical features like `Embarked` and `Pclass` (if treated as categorical rather than ordinal).

Let's apply Label Encoding to the `Sex` column and One-Hot Encoding to the `Embarked` column. We will also drop the original `Name`, `Ticket`, and `Cabin` columns as they are either unique identifiers, have too many categories, or are already captured by `Cabin_Known`.
"""

import pandas as pd

# --- Re-applying essential preprocessing to ensure DataFrame consistency ---
# Reload the original dataset to ensure all columns are present
titanic = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

# Impute missing 'Age' values with the median
median_age = titanic['Age'].median()
titanic['Age'] = titanic['Age'].fillna(median_age)

# Create 'Cabin_Known' feature from 'Cabin' column
titanic['Cabin_Known'] = titanic['Cabin'].apply(lambda x: 0 if pd.isnull(x) else 1)

# Impute missing 'Embarked' values with the mode
most_frequent_embarked = titanic['Embarked'].mode()[0]
titanic['Embarked'] = titanic['Embarked'].fillna(most_frequent_embarked)
# -------------------------------------------------------------------------

# Label Encoding for 'Sex' column
titanic['Sex'] = titanic['Sex'].map({'male': 0, 'female': 1})

# One-Hot Encoding for 'Embarked' column
titanic = pd.get_dummies(titanic, columns=['Embarked'], drop_first=True, dtype=int)

# Drop columns that are not useful for modeling or have been processed
titanic.drop(columns=['Name', 'Ticket', 'Cabin'], inplace=True)

print("DataFrame after categorical encoding and column drops:")
print(titanic.head())
print(f"\nNew shape of the DataFrame: {titanic.shape}")
print("\nData types after encoding:")
titanic.info()

"""### E. Feature Scaling

**Why is scaling important in machine learning?**

Feature scaling is a crucial preprocessing step in machine learning for several reasons:
1.  **Algorithm Performance:** Many machine learning algorithms (e.g., K-Nearest Neighbors, Support Vector Machines, neural networks, linear/logistic regression with gradient descent) are sensitive to the scale of input features. If features have vastly different ranges, features with larger values might dominate the distance calculations or cost functions, leading to suboptimal model performance.
2.  **Convergence Speed:** For optimization algorithms like gradient descent, scaling can help them converge faster to the optimal solution by preventing oscillations caused by varying feature scales.
3.  **Regularization:** In models using regularization techniques (like L1 or L2 regularization), scaling ensures that the penalty is applied equally to all features, preventing features with larger scales from being overly penalized or under-penalized.
4.  **Interpretability:** While not always the primary goal, scaling can sometimes make coefficients in linear models more comparable, aiding in feature importance interpretation.

We will apply **StandardScaler** to the numerical columns. StandardScaler transforms data to have a mean of 0 and a standard deviation of 1. This is a common and robust scaling method, especially when the data distribution is approximately Gaussian or when the algorithm assumes normally distributed data.

Standardization is a feature scaling technique that transforms numerical data by subtracting the mean and dividing by the standard deviation. The process results in a variable with a mean of 0 and a standard deviation of 1,allowing features with different scales to be compared fairly by the ML algorithms.ok so
"""

from sklearn.preprocessing import StandardScaler

# Identify numerical columns to scale
# Exclude 'PassengerId' as it's an identifier
# Exclude 'Survived' as it's the target variable
# 'Sex', 'Cabin_Known', 'Embarked_Q', 'Embarked_S' are already binary (0/1) and don't typically need scaling for most models
# 'Pclass' is ordinal, sometimes scaled, sometimes left as is. For now, let's scale it as it represents a 'level'.

columns_to_scale = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply scaling to the selected columns
titanic[columns_to_scale] = scaler.fit_transform(titanic[columns_to_scale])

print("DataFrame after Feature Scaling (StandardScaler) for selected numerical columns:")
print(titanic.head())
print("\nDescriptive statistics for scaled columns:")
print(titanic[columns_to_scale].describe())

"""## Part 3: Exploratory Data Analysis (EDA)

### A. Univariate Analysis

Univariate analysis focuses on understanding the distribution of each variable in the dataset independently. This helps us identify central tendencies, spread, skewness, and potential outliers for numerical data, and frequency counts for categorical data.
"""

import matplotlib.pyplot as plt
import seaborn as sns

print('--- Univariate Analysis ---')

# 1. Distribution of the Target Variable: Survived
plt.figure(figsize=(6, 4))
sns.countplot(x='Survived', data=titanic, palette='viridis')
plt.title('Distribution of Survived (0 = No, 1 = Yes)')
plt.xlabel('Survived')
plt.ylabel('Number of Passengers')
plt.xticks(ticks=[0, 1], labels=['Not Survived', 'Survived'])
plt.show()

print('\nSurvival Count:')
print(titanic['Survived'].value_counts(normalize=True) * 100)

"""### Univariate Analysis of Numerical Features

Let's examine the distributions of the scaled numerical features: `Pclass`, `Age`, `SibSp`, `Parch`, and `Fare`. Histograms and Kernel Density Estimate (KDE) plots are useful for this purpose.
"""

# 2. Distribution of Scaled Numerical Features
numerical_cols_scaled = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

plt.figure(figsize=(18, 12))
for i, col in enumerate(numerical_cols_scaled):
    plt.subplot(3, 2, i + 1) # Adjust subplot grid as needed
    sns.histplot(titanic[col], kde=True, bins=30, palette='viridis')
    plt.title(f'Distribution of Scaled {col}')
    plt.xlabel(f'Scaled {col}')
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

print('\nDescriptive statistics for scaled numerical features:')
display(titanic[numerical_cols_scaled].describe())

"""### Univariate Analysis of Categorical/Binary Features

Now, let's look at the distributions of our binary and one-hot encoded categorical features: `Sex`, `Cabin_Known`, `Embarked_Q`, and `Embarked_S`.
"""

# 3. Distribution of Binary/Categorical Features
binary_categorical_cols = ['Sex', 'Cabin_Known', 'Embarked_Q', 'Embarked_S']

plt.figure(figsize=(15, 5))
for i, col in enumerate(binary_categorical_cols):
    plt.subplot(1, 4, i + 1)
    sns.countplot(x=col, data=titanic, palette='cividis')
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Number of Passengers')
    if col == 'Sex':
        plt.xticks(ticks=[0, 1], labels=['Male', 'Female'])
    elif col == 'Cabin_Known':
        plt.xticks(ticks=[0, 1], labels=['Unknown', 'Known'])
    elif col == 'Embarked_Q':
        plt.xticks(ticks=[0, 1], labels=['Not Q', 'Q'])
    elif col == 'Embarked_S':
        plt.xticks(ticks=[0, 1], labels=['Not S', 'S'])

plt.tight_layout()
plt.show()

print('\nValue counts for binary/categorical features:')
for col in binary_categorical_cols:
    print(f'\n{col}:')
    print(titanic[col].value_counts(normalize=True) * 100)

"""### B. Bivariate Analysis

Bivariate analysis explores the relationship between pairs of variables. Our primary focus here will be to understand how each feature relates to our target variable: `Survived`.

#### Bivariate Analysis with Categorical/Binary Features vs. Survival

Let's visualize the survival rate across different categories of our binary and one-hot encoded features.
"""

print('--- Bivariate Analysis: Categorical/Binary Features vs. Survival ---')

categorical_for_bivariate = ['Sex', 'Pclass', 'Cabin_Known', 'Embarked_Q', 'Embarked_S']

plt.figure(figsize=(18, 10))
for i, col in enumerate(categorical_for_bivariate):
    plt.subplot(2, 3, i + 1)
    sns.barplot(x=col, y='Survived', data=titanic, palette='pastel')
    plt.title(f'Survival Rate by {col}')
    plt.xlabel(col)
    plt.ylabel('Survival Rate')
    if col == 'Sex':
        plt.xticks(ticks=[0, 1], labels=['Male', 'Female'])
    elif col == 'Cabin_Known':
        plt.xticks(ticks=[0, 1], labels=['Unknown', 'Known'])
    elif col == 'Embarked_Q':
        plt.xticks(ticks=[0, 1], labels=['Not Q', 'Q'])
    elif col == 'Embarked_S':
        plt.xticks(ticks=[0, 1], labels=['Not S', 'S'])
plt.tight_layout()
plt.show()

print('\nSurvival rates by categorical features:')
for col in categorical_for_bivariate:
    print(f'\nSurvival Rate by {col}:')
    print(titanic.groupby(col)['Survived'].mean() * 100)

"""#### Bivariate Analysis with Numerical Features vs. Survival

For numerical features, we can look at their distribution conditioned on survival, or analyze correlations. Histograms/KDE plots split by 'Survived' can reveal differences, and a correlation matrix can show linear relationships.
"""

print('\n--- Bivariate Analysis: Numerical Features vs. Survival ---')

numerical_for_bivariate = ['Age', 'SibSp', 'Parch', 'Fare']

# Distribution of numerical features for survived vs. not survived
plt.figure(figsize=(18, 12))
for i, col in enumerate(numerical_for_bivariate):
    plt.subplot(2, 2, i + 1)
    sns.histplot(data=titanic, x=col, hue='Survived', kde=True, bins=30, palette='coolwarm')
    plt.title(f'Distribution of Scaled {col} by Survival')
    plt.xlabel(f'Scaled {col}')
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

# Correlation Matrix for numerical features including Survived
print('\nCorrelation Matrix with Survived:')
# Drop 'PassengerId' as it's an identifier and not a predictive feature
correlation_matrix = titanic.drop('PassengerId', axis=1).corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of All Features with Survived')
plt.show()

print('\nCorrelation of features with Survived:')
print(correlation_matrix['Survived'].sort_values(ascending=False))

"""## Save the Cleaned Dataset

Now that the data preprocessing and exploratory data analysis are complete, we will save the cleaned `titanic` DataFrame to a CSV file. This allows us to easily load this prepared dataset for future steps, such as model training, without needing to re-run all the preprocessing steps.
"""

output_file_name = 'titanic_cleaned.csv'
titanic.to_csv(output_file_name, index=False)

print(f"Cleaned dataset saved to '{output_file_name}'")
print("First 25 rows of the saved data:")
display(pd.read_csv(output_file_name).head())

display(titanic)

titanic.to_csv('titanic_cleaned_final.csv', index=False)

from google.colab import files

files.download('titanic_cleaned_final.csv')

"""# **INTRODUCTION**

 Dataset Overview
The dataset contained information about the titanic Passenger List with a sample size of 891 passengers.
The data also had 12 variables (including target) and the target variable was Survived (0 = Died, 1 = Survived)
The objective was to analyze passenger information and identify factors that may influence survival outcomes.


**# DATA PREPROCESSING**

 **Missing Value Treatment**

Missing values were identified in the AGE,EMBARKED AND CABIN variables and we used different treatment methods depending on the nature of the variable.

**AGE**

The age variable had a total of 177 missing values which were imputed using the median.Median imputation was chosen because age contained outliers and the median is more robust than the mean as it is less sensitive to extreme values.

**EMBARKED**

During investigation of the 2 missing values under embarked i observed that the passengers shared the same ticket, fare and cabin ,suggesting that they were travelling together.Since the embarkation port could not be determined with ceternanty , the missing values were imputed using the mode.  

**CABIN**

The cabin variable contained 687 missing values and instead of imputing cabin numbers , a binary feature called Cabin_Known was created, where a value of 1 was assigned to show that cabin information was available and 0 meaning that cabin information was missing.The assignment preserves the information contained in the missingness itself without introducing potentially inaccurate cabin information through imputation.


**Duplicate Removal**

The dataset had no duplicate values.

 **Outlier Treatment**

Outliers were identified using the IQR method but were retained because they represented real data points-older passengers, large families, and high fares-rather than errors. Removing them would have lost valuable information about passenger diversity and survival patterns.



**Feature Encoding**

1. **Sex:** Label Encoding
   - Male → 0
   - Female → 1

2. **Embarked:** One-Hot Encoding
   - Embarked_C, Embarked_Q, Embarked_S


**Scaling**

Standard scaling was used on the numerical variabkles to ensure that they were measured on a common scale.Standard scaling improves the performance of algorithms that are sensitive to the scale of input features, ensuring that each numerical value contributes more equally during model training.

**EDA**

 Bar plots showed significant relationships:
Sex: Females had a significantly higher survival rate (around 74%) compared to males (around 19%).
Pclass: First-class passengers had the highest survival rate (around 63%), followed by second-class (around 47%), and then third-class (around 24%).
Cabin_Known: Passengers with known cabin information had a much higher survival rate (around 67%) than those without (around 30%).
Embarked_Q and Embarked_S: The survival rates varied slightly by embarkation point, with passengers not embarking from Southampton ('Not S', which includes 'C' and 'Q') having a higher survival rate than those from Southampton.
Numerical Features vs. Survival:
Distributions by Survival: Histograms split by Survived revealed differences. For instance, younger passengers and those who paid higher fares seemed to have a higher chance of survival. Passengers with more SibSp and Parch (larger family sizes) showed varying survival patterns.
Correlation Matrix: A heatmap of the correlation matrix, including Survived, highlighted key linear relationships:
Strong positive correlation of Sex with Survived (0.54), confirming females had better survival chances.
Positive correlation of Cabin_Known with Survived (0.32).
Positive correlation of Fare with Survived (0.26).
Negative correlation of Pclass with Survived (-0.34), indicating higher class was associated with higher survival.
Overall, the EDA confirmed that features like Sex, Pclass, Cabin_Known, and Fare are strong indicators of survival, providing valuable insights for subsequent model building.

## Visualizations of Original Dataset (Before Preprocessing)

Let's visualize some key features from the `titanic_df` (the original, uncleaned dataset) to understand its initial state and distributions.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set up the figure and axes for the plots
plt.figure(figsize=(18, 12))

# --- Numerical Features (Histograms) ---

# Age distribution
plt.subplot(2, 3, 1)
sns.histplot(titanic_df['Age'].dropna(), kde=True, bins=30)
plt.title('Distribution of Age (Original)')
plt.xlabel('Age')
plt.ylabel('Frequency')

# Fare distribution
plt.subplot(2, 3, 2)
sns.histplot(titanic_df['Fare'], kde=True, bins=30)
plt.title('Distribution of Fare (Original)')
plt.xlabel('Fare')
plt.ylabel('Frequency')

# --- Categorical Features (Count Plots) ---

# Sex distribution
plt.subplot(2, 3, 3)
sns.countplot(x='Sex', data=titanic_df, palette='viridis', hue='Sex', legend=False)
plt.title('Distribution of Sex (Original)')
plt.xlabel('Sex')
plt.ylabel('Count')

# Pclass distribution
plt.subplot(2, 3, 4)
sns.countplot(x='Pclass', data=titanic_df, palette='magma', hue='Pclass', legend=False)
plt.title('Distribution of Pclass (Original)')
plt.xlabel('Passenger Class')
plt.ylabel('Count')

# Embarked distribution
plt.subplot(2, 3, 5)
sns.countplot(x='Embarked', data=titanic_df, palette='cividis', hue='Embarked', legend=False)
plt.title('Distribution of Embarked (Original)')
plt.xlabel('Port of Embarkation')
plt.ylabel('Count')

plt.tight_layout()
plt.show()

"""## Survival Comparison: Survivors vs. Non-Survivors

These visualizations compare the characteristics of passengers who survived (`Survived = 1`) versus those who did not (`Survived = 0`) across key features from the preprocessed `titanic` dataset.
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(18, 12))

# Comparison of Sex by Survival
plt.subplot(2, 2, 1)
sns.countplot(x='Sex', hue='Survived', data=titanic, palette='viridis')
plt.title('Survival Count by Sex (0=Male, 1=Female)')
plt.xlabel('Sex')
plt.ylabel('Number of Passengers')
plt.xticks(ticks=[0, 1], labels=['Not Survived', 'Survived']) # Correcting x-labels to Sex categories

# Comparison of Pclass by Survival
plt.subplot(2, 2, 2)
sns.countplot(x='Pclass', hue='Survived', data=titanic, palette='magma')
plt.title('Survival Count by Passenger Class')
plt.xlabel('Passenger Class (Scaled)')
plt.ylabel('Number of Passengers')

# Distribution of Age by Survival
plt.subplot(2, 2, 3)
sns.histplot(data=titanic, x='Age', hue='Survived', kde=True, bins=30, palette='coolwarm')
plt.title('Distribution of Age by Survival')
plt.xlabel('Age (Scaled)')
plt.ylabel('Frequency')

# Distribution of Fare by Survival
plt.subplot(2, 2, 4)
sns.histplot(data=titanic, x='Fare', hue='Survived', kde=True, bins=30, palette='coolwarm')
plt.title('Distribution of Fare by Survival')
plt.xlabel('Fare (Scaled)')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

"""## Key Presentation Graphs: The Story of Titanic Survival

These graphs consolidate the most impactful visualizations from our Exploratory Data Analysis, chosen to effectively communicate the primary factors influencing survival on the Titanic for a concise presentation.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure the 'titanic' DataFrame is loaded and preprocessed
# (This code assumes 'titanic' DataFrame with 'Survived', 'Sex', 'Pclass', 'Age', 'Fare', 'Cabin_Known' and scaled features is available from previous steps)
# If running this cell independently, ensure the preprocessing cells are run first or reload the 'titanic_cleaned.csv'

# Load the cleaned dataset if not already in memory
try:
    titanic = pd.read_csv('titanic_cleaned.csv')
except FileNotFoundError:
    print("titanic_cleaned.csv not found. Please ensure preprocessing cells are run.")
    # Fallback to recreate (simplified, assumes original csv path)
    titanic = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
    median_age = titanic['Age'].median()
    titanic['Age'].fillna(median_age, inplace=True)
    titanic['Cabin_Known'] = titanic['Cabin'].apply(lambda x: 0 if pd.isnull(x) else 1)
    most_frequent_embarked = titanic['Embarked'].mode()[0]
    titanic['Embarked'].fillna(most_frequent_embarked, inplace=True)
    titanic['Sex'] = titanic['Sex'].map({'male': 0, 'female': 1})
    titanic = pd.get_dummies(titanic, columns=['Embarked'], drop_first=True, dtype=int)
    titanic.drop(columns=['Name', 'Ticket', 'Cabin'], inplace=True)
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    columns_to_scale = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
    titanic[columns_to_scale] = scaler.fit_transform(titanic[columns_to_scale])


# --- 1. Overall Survival Rate ---
plt.figure(figsize=(6, 4))
sns.countplot(x='Survived', data=titanic, palette='viridis')
plt.title('1. Overall Survival Rate on the Titanic')
plt.xlabel('Survival Status')
plt.ylabel('Number of Passengers')
plt.xticks(ticks=[0, 1], labels=['Perished (0)', 'Survived (1)'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# --- 2. Survival Rate by Sex and Passenger Class (Combined for Impact) ---
plt.figure(figsize=(10, 6))
sns.barplot(x='Pclass', y='Survived', hue='Sex', data=titanic, palette='coolwarm')
plt.title('2. Survival Rate by Passenger Class and Sex')
plt.xlabel('Passenger Class (Scaled)')
plt.ylabel('Survival Rate')
# Custom Pclass labels for better interpretation if desired, based on scaled values. Assuming original Pclass 1, 2, 3 corresponds to scaled values.
# If you want to show original Pclass, you'd need to inverse transform or use the original 'Pclass' before scaling for this plot.
# For now, we use scaled Pclass values as generated by the script but you might want to interpret them for your audience.
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# --- 3. Survival Rate by Cabin_Known ---
plt.figure(figsize=(7, 5))
sns.barplot(x='Cabin_Known', y='Survived', data=titanic, palette='pastel')
plt.title('3. Survival Rate by Cabin Information Availability')
plt.xlabel('Cabin Information (0=Unknown, 1=Known)')
plt.ylabel('Survival Rate')
plt.xticks(ticks=[0, 1], labels=['Cabin Unknown', 'Cabin Known'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# --- 4. Distribution of Age by Survival ---
plt.figure(figsize=(8, 5))
sns.histplot(data=titanic, x='Age', hue='Survived', kde=True, bins=30, palette='viridis', common_norm=False)
plt.title('4. Distribution of Age (Scaled) by Survival Status')
plt.xlabel('Age (Scaled)')
plt.ylabel('Density / Count')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# --- 5. Distribution of Fare by Survival ---
plt.figure(figsize=(8, 5))
sns.histplot(data=titanic, x='Fare', hue='Survived', kde=True, bins=30, palette='magma', common_norm=False)
plt.title('5. Distribution of Fare (Scaled) by Survival Status')
plt.xlabel('Fare (Scaled)')
plt.ylabel('Density / Count')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# --- 6. Correlation Matrix (Focus on Survived) ---
plt.figure(figsize=(10, 8))
correlation_matrix = titanic.drop('PassengerId', axis=1).corr()
sns.heatmap(correlation_matrix[['Survived']].sort_values(by='Survived', ascending=False), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('6. Feature Correlations with Survival')
plt.xlabel('Features')
plt.ylabel('Features')
plt.tight_layout()
plt.show()